import test from 'node:test';
import assert from 'node:assert/strict';
import {deleteRecord,deleteMemberAccount} from '../lib/deletion.ts';
function database({data={id:'post-id'},error=null,linkError=null}={}){
 const calls=[];let table,action;
 const chain={delete(){action='delete';calls.push(['delete',table]);return this},update(value){action='update';calls.push(['update',table,value]);return this},eq(key,value){calls.push(['eq',key,value]);return this},select(value){calls.push(['select',value]);return this},maybeSingle(){return Promise.resolve({data,error})},then(resolve){return Promise.resolve({error:action==='update'?linkError:error}).then(resolve)}};
 return {calls,from(name){table=name;calls.push(['from',name]);return chain}};
}
test('post deletion removes the row and constrains member ownership',async()=>{const db=database();const result=await deleteRecord(db,'posts','post-id','author-id');assert.equal(result.data.id,'post-id');assert.deepEqual(db.calls,[['from','posts'],['delete','posts'],['eq','id','post-id'],['eq','author_id','author-id'],['select','id']]);});
test('zero affected rows and database failures cannot masquerade as deletion',async()=>{assert.equal((await deleteRecord(database({data:null}),'posts','missing')).data,null);const error={message:'denied'};assert.equal((await deleteRecord(database({data:null,error}),'posts','post-id')).error,error);});
test('member deletion preserves organization nodes by detaching the profile first',async()=>{const db=database();await deleteRecord(db,'members','member-id');assert.deepEqual(db.calls.slice(0,3),[['from','organization_nodes'],['update','organization_nodes',{member_id:null}],['eq','member_id','member-id']]);assert.deepEqual(db.calls.slice(3),[['from','members'],['delete','members'],['eq','id','member-id'],['select','id']]);});
test('failed organization unlink stops member deletion',async()=>{const db=database({linkError:{message:'denied'}});assert.ok((await deleteRecord(db,'members','member-id')).error);assert.equal(db.calls.some(call=>call[0]==='delete'),false);});

test('linked member deletion removes the account atomically instead of leaving an approved identity',async()=>{const db=database({data:{id:'member-id',user_id:'user-id'}});db.rpc=async(name,args)=>{db.calls.push(['rpc',name,args]);return {error:null}};const result=await deleteMemberAccount(db,'member-id');assert.deepEqual(result.data,{id:'member-id'});assert.deepEqual(db.calls.at(-1),['rpc','withdraw_lab_account',{target_user:'user-id'}]);assert.equal(db.calls.some(call=>call[0]==='delete'),false)});
test('protected account and transaction failures never report member deletion success',async()=>{const db=database({data:{id:'member-id',user_id:'admin-id'}});db.rpc=async()=>({error:{message:'Transfer administrator access first'}});const result=await deleteMemberAccount(db,'member-id');assert.equal(result.data,null);assert.match(result.error.message,/administrator/);assert.equal(db.calls.some(call=>call[0]==='delete'),false)});
test('unknown member IDs never invoke account deletion',async()=>{const db=database({data:null});db.rpc=()=>{throw Error('must not run')};const result=await deleteMemberAccount(db,'missing');assert.equal(result.data,null)});

test('publication bulk deletion targets selected IDs and exposes affected rows and failures',async()=>{const {deletePublications}=await import('../lib/deletion.ts');const calls=[];const ids=['one','two'];const db={from(table){calls.push(table);return {delete(){calls.push('delete');return this},in(field,values){calls.push([field,values]);return this},select(field){calls.push(field);return Promise.resolve({data:[{id:'one'}],error:null})}}}};const result=await deletePublications(db,ids);assert.deepEqual(result.data,[{id:'one'}]);assert.deepEqual(calls,['publications','delete',['id',ids],'id']);const denied={from(){return {delete(){return this},in(){return this},select(){return Promise.resolve({data:null,error:{message:'permission denied'}})}}}};assert.equal((await deletePublications(denied,ids)).error.message,'permission denied')});
