import test from 'node:test';
import assert from 'node:assert/strict';
import {ensureMemberApplication} from '../lib/member-application.ts';
function database(profile=null,member=null){const rows={profile,member};return {rows,from(table){return {async upsert(value){const key=table==='profiles'?'profile':'member';rows[key]??=value;return {error:null}},select(){return {eq(){return {async maybeSingle(){return {data:table==='profiles'?rows.profile:rows.member,error:null}},async single(){return {data:rows.profile,error:null}}}}}}}}}}
const user={id:'user-a',email:'test@example.com',email_confirmed_at:'2026-10-09',user_metadata:{display_name:'테스트',lab_role:'Postdoc',public_email:false}};
test('missing signup trigger rows are repaired as pending and invisible despite verified email',async()=>{const db=database();await ensureMemberApplication(db,user);assert.equal(db.rows.profile.membership_status,'pending');assert.equal(db.rows.profile.role,'viewer');assert.equal(db.rows.member.role,'Postdoc');assert.equal(db.rows.member.is_visible,false);assert.equal(db.rows.member.email,null)});
test('repair never changes an existing approval or member visibility',async()=>{const profile={role:'viewer',membership_status:'rejected'},member={name:'기존 이름',is_visible:false};const db=database(profile,member);await ensureMemberApplication(db,user);assert.equal(db.rows.profile,profile);assert.equal(db.rows.member,member)});
test('missing member may become visible only when an existing administrator approval and verified email both exist',async()=>{const db=database({role:'viewer',membership_status:'approved'});await ensureMemberApplication(db,user);assert.equal(db.rows.member.is_visible,true);const unverified=database({role:'viewer',membership_status:'approved'});await ensureMemberApplication(unverified,{...user,email_confirmed_at:null});assert.equal(unverified.rows.member.is_visible,false)});
test('untrusted role metadata cannot create an administrator or professor application',async()=>{for(const role of ['admin','owner','Professor']){const db=database();await assert.rejects(ensureMemberApplication(db,{...user,user_metadata:{...user.user_metadata,lab_role:role}}));assert.equal(db.rows.profile,null)}});

test('existing manually configured member accounts need no signup metadata to log in',async()=>{const db=database({role:'viewer',membership_status:'approved'},{name:'수동 등록',is_visible:true});await ensureMemberApplication(db,{...user,user_metadata:{}});assert.equal(db.rows.member.name,'수동 등록')});
