import test from 'node:test';import assert from 'node:assert/strict';
import {readHistory,settingsSchemas,groupHistory} from '../lib/site-settings.ts';import {citationDetails,parseSearchArticles} from '../lib/scholar.ts';import {profileDetailsSchema,publicProfileDetails} from '../lib/profile-details.ts';
test('history preserves date grouping and indent order without replacing legacy content during read',()=>{const rows=[{date:'2026.03',events:['첫 이력','두 번째 이력']},{date:'2025',events:['설립']}];assert.deepEqual(readHistory(JSON.stringify({entries:rows})),rows);assert.equal(readHistory('기존 연혁 텍스트'),null);assert.equal(settingsSchemas.history.safeParse({entries:[{date:'',events:['내용']}]}).success,false);assert.equal(settingsSchemas.history.safeParse({entries:[{date:'2026',events:[]}]}).success,false);});
test('auth artwork accepts uploaded images and rejects active content protocols',()=>{assert.equal(settingsSchemas.auth.safeParse({image:'/api/media/lab/banner.webp'}).success,true);assert.equal(settingsSchemas.auth.safeParse({image:'javascript:alert(1)'}).success,false)});
test('Scholar details use actual provider summary and journal and tolerate missing metadata',()=>{assert.deepEqual(citationDetails({citation:{description:'Actual abstract',journal:'Statistics Journal'}}),{summary:'Actual abstract',venue:'Statistics Journal'});assert.deepEqual(citationDetails({}),{summary:'',venue:''});assert.equal(parseSearchArticles({organic_results:[{result_id:'one',title:'Test',snippet:'Provider snippet'}]})[0].summary,'Provider snippet');});
test('alumni affiliation and position are published while private contact fields stay hidden',()=>{const details=profileDetailsSchema.parse({current_affiliation:'Company',current_position:'Analyst',phone:'010-private',student_id:'private'});const published=publicProfileDetails(details);assert.equal(published.current_affiliation,'Company');assert.equal(published.current_position,'Analyst');assert.equal(published.phone,'');assert.equal(published.student_id,'')});

test('history sorts mixed Korean and dotted dates newest first with stable same-date order',()=>{const rows=[{date:'2025.12',events:['old']},{date:'2026년 2월 1일',events:['feb']},{date:'2026.10.09',events:['latest']},{date:'2026.10.09',events:['same day second']}];const sorted=readHistory(JSON.stringify({entries:rows}));assert.deepEqual(sorted.map(x=>x.events),[['latest','same day second'],['feb'],['old']]);assert.equal(rows[0].date,'2025.12')});

test('history merges equivalent months, keeps year-only groups separate and preserves all events',()=>{const rows=[{date:'2026.03',events:['first']},{date:'2026년 3월',events:['second']},{date:'2026.03.20',events:['third']},{date:'2026',events:['year']}];assert.deepEqual(groupHistory(rows),[{date:'2026.03',events:['third','first','second']},{date:'2026',events:['year']}]);assert.deepEqual(rows[0].events,['first']);});
test('merged history groups remain readable when duplicate months previously had over 30 events',()=>{const entries=[{date:'2026.03',events:Array.from({length:30},(_,i)=>'A'+i)},{date:'2026년 3월',events:Array.from({length:30},(_,i)=>'B'+i)}];const merged=groupHistory(entries);assert.equal(readHistory(JSON.stringify({entries:merged}))[0].events.length,60);});
