import {NextRequest,NextResponse} from 'next/server';
import {currentAccount} from '@/lib/supabase';
import {canWriteBoard,canManagePost,isAdministrator} from '@/lib/permissions';
import {z} from 'zod';
import {revalidatePath,revalidateTag} from 'next/cache';
const schema=z.object({id:z.string().uuid().optional(),title:z.string().trim().min(1).max(250),body:z.string().max(200000),category:z.string().min(1).max(180),status:z.enum(['draft','published'])});
export async function POST(req:NextRequest){return save(req,false)}
export async function PATCH(req:NextRequest){return save(req,true)}
async function save(req:NextRequest,updating:boolean){const account=await currentAccount();if(!account)return NextResponse.json({error:'로그인이 필요합니다.'},{status:401});const p=schema.safeParse(await req.json().catch(()=>null));if(!p.success)return NextResponse.json({error:'제목과 본문을 확인해주세요.'},{status:400});if(!canWriteBoard(account,p.data.category))return NextResponse.json({error:'이 게시판의 작성 권한이 없습니다.'},{status:403});let old:any=null;if(updating){if(!p.data.id)return NextResponse.json({error:'게시글을 확인해주세요.'},{status:400});const {data}=await account.db.from('posts').select('*').eq('id',p.data.id).maybeSingle();old=data;if(!old||!canManagePost(account,old))return NextResponse.json({error:'이 글을 수정할 권한이 없습니다.'},{status:403});}
const data:Record<string,unknown>={title:p.data.title,body:p.data.body,excerpt:p.data.body.slice(0,150),category:p.data.category,status:p.data.status,published_at:p.data.status==='published'?(old?.published_at||new Date().toISOString()):old?.published_at||null};if(!updating){data.author_id=account.user.id;data.slug=crypto.randomUUID();}const q=account.db.from('posts');const result=updating?await q.update(data).eq('id',p.data.id!).select().single():await q.insert(data).select().single();if(result.error)return NextResponse.json({error:result.error.message.includes('author_id')?'게시판 설정 SQL(002_membership.sql)을 먼저 적용해주세요.':'저장하지 못했습니다. 권한과 데이터베이스 설정을 확인해주세요.'},{status:400});revalidateTag('lab-public');revalidatePath('/','layout');return NextResponse.json({data:result.data})}
export async function DELETE(req:NextRequest){const account=await currentAccount();if(!account)return NextResponse.json({error:'로그인이 필요합니다.'},{status:401});const p=z.object({id:z.string().uuid()}).safeParse(await req.json().catch(()=>null));if(!p.success)return NextResponse.json({error:'게시글을 확인해주세요.'},{status:400});const {data:post}=await account.db.from('posts').select('*').eq('id',p.data.id).maybeSingle();if(!post||!canManagePost(account,post))return NextResponse.json({error:'이 글을 삭제할 권한이 없습니다.'},{status:403});const {error}=await account.db.from('posts').update({status:'draft'}).eq('id',post.id);if(error)return NextResponse.json({error:'삭제하지 못했습니다.'},{status:400});revalidateTag('lab-public');revalidatePath('/','layout');return NextResponse.json({ok:true})}
