import {NextRequest,NextResponse} from 'next/server';
import {requireAdmin} from '@/lib/supabase';
import {revalidatePath,revalidateTag} from 'next/cache';
import {z} from 'zod';import {contentSchema as schema} from '@/lib/content-schema';
const tables=['posts','pages','members','publications'] as const;
function refresh(){revalidateTag('lab-public');revalidatePath('/','layout')}
export async function GET(request:NextRequest){const ctx=await requireAdmin();if(!ctx)return NextResponse.json({error:'Unauthorized'},{status:401});const type=request.nextUrl.searchParams.get('type');if(!tables.includes(type as typeof tables[number]))return NextResponse.json({error:'Invalid type'},{status:400});const {data,error}=await ctx.db.from(type!).select('*').limit(500);return NextResponse.json(error?{error:error.message}:{data},{status:error?500:200})}
export async function POST(req:NextRequest){return save(req,false)}
export async function PATCH(req:NextRequest){return save(req,true)}
async function save(req:NextRequest,updating:boolean){const ctx=await requireAdmin();if(!ctx)return NextResponse.json({error:'Unauthorized'},{status:401});const parsed=schema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:parsed.error.issues.map(i=>i.message).join(', ')},{status:400});const p=parsed.data;if(updating&&!p.id)return NextResponse.json({error:'ID required'},{status:400});let data:Record<string,unknown>;
if(p.type==='members'){data={name:p.title,bio:p.body,is_visible:p.status==='published'};for(const key of ['role','name_en','email','photo_url','scholar_author_id','sort_order'] as const)if(p[key]!==undefined)data[key]=p[key];}
else if(p.type==='publications'){data={title:p.title,status:p.status};for(const key of ['authors','year','venue','doi','paper_url'] as const)if(p[key]!==undefined)data[key]=p[key]||null;if(!updating&&!p.authors)data.authors=[];}
else if(p.type==='pages'){if(!p.slug)return NextResponse.json({error:'페이지 경로가 필요합니다.'},{status:400});data={title:p.title,slug:p.slug,body:p.body,status:p.status,updated_at:new Date().toISOString()};if(p.lead!==undefined)data.lead=p.lead;}
else {data={title:p.title,body:p.body,excerpt:p.body.slice(0,150),status:p.status};if(p.slug)data.slug=p.slug;else if(!updating)data.slug=crypto.randomUUID();if(p.category)data.category=p.category;if(p.status==='published'){if(!updating)data.published_at=new Date().toISOString();else {const {data:old}=await ctx.db.from('posts').select('published_at').eq('id',p.id!).single();if(!old?.published_at)data.published_at=new Date().toISOString();}}}
const q=ctx.db.from(p.type);const result=updating?await q.update(data).eq('id',p.id!).select().single():await q.insert(data).select().single();if(!result.error)refresh();return NextResponse.json(result.error?{error:result.error.message}:{data:result.data},{status:result.error?400:200})}
// Removal is reversible: records are unpublished and remain editable in the CMS.
export async function DELETE(req:NextRequest){const ctx=await requireAdmin();if(!ctx)return NextResponse.json({error:'Unauthorized'},{status:401});const p=z.object({type:z.enum(tables),id:z.string().uuid()}).safeParse(await req.json().catch(()=>null));if(!p.success)return NextResponse.json({error:'Invalid body'},{status:400});const {error}=await ctx.db.from(p.data.type).update(p.data.type==='members'?{is_visible:false}:{status:'draft'}).eq('id',p.data.id);if(!error)refresh();return NextResponse.json(error?{error:error.message}:{ok:true},{status:error?400:200})}
