"use client";
import dynamic from 'next/dynamic';import PublishSwitch from './PublishSwitch';
const RichEditor=dynamic(()=>import('./RichEditor'),{ssr:false,loading:()=> <div className="rich-editor-loading">에디터를 불러오는 중…</div>});
import {useEffect,useState} from 'react';
import {editableStrings} from '@/lib/editor';
import {sections} from '@/lib/content';import {professorBiography} from '@/lib/professor';
import ImageUpload from './ImageUpload';
export {default as ImageUpload} from './ImageUpload';
type Item=Record<string,any>;
const initial={title:'',slug:'',body:'',lead:'',category:'notice',status:'draft',role:'Masters',name_en:'',email:'',photo_url:'',scholar_author_id:'',sort_order:100,authors:'',year:'',venue:'',doi:'',paper_url:''};
const roles=[['Professor','교수'],['Postdoc','박사후연구원'],['PhD','박사과정'],['Masters','석사과정'],['Undergraduate','학부연구생'],['Alumni','졸업생'],['Researcher','연구원']];
export default function AdminEditor({initialType='posts',initialSlug='',initialCategory='notice',initialId='',focused=false}:{initialType?:string;initialSlug?:string;initialCategory?:string;initialId?:string;focused?:boolean}){
const [type,setType]=useState(initialType),[form,setForm]=useState<Item>({...initial,slug:initialSlug,category:initialCategory}),[msg,setMsg]=useState(''),[list,setList]=useState<Item[]>([]),[editId,setEditId]=useState(initialId),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[confirmId,setConfirmId]=useState(''),[uploading,setUploading]=useState(false),[failed,setFailed]=useState(false);
const field=(key:string,value:any)=>setForm(f=>({...f,[key]:value}));
function edit(it:Item){setFailed(false);setEditId(it.id);setForm({...initial,...it,...editableStrings(it),sort_order:it.sort_order??100,title:it.title||it.name,body:it.name==='이광민'&&(!it.bio||it.bio==='전남대학교 통계학과 조교수')?professorBiography:it.body||it.bio||'',status:it.is_visible===undefined?it.status:it.is_visible?'published':'draft',role:it.role==='Principal Investigator'?'Professor':it.role||'Masters',authors:(it.authors||[]).join('\n'),year:it.year||''});setMsg('편집 중: '+(it.title||it.name));}
async function load(){setLoading(true);try{const r=await fetch('/api/v1/admin/content?type='+type);const j=await r.json();if(!r.ok)throw Error(j.error);setList(j.data||[]);return j.data as Item[];}catch(e){setFailed(true);setMsg(e instanceof Error?e.message:'조회 실패');return [];}finally{setLoading(false)}}
useEffect(()=>{let active=true;load().then(items=>{if(!active)return;const found=items.find(it=>initialId?it.id===initialId:initialSlug&&it.slug===initialSlug);if(found)edit(found);});return()=>{active=false};},[type]);
async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setFailed(false);setMsg('저장 중...');try{const data={...form,type,id:editId||undefined,authors:String(form.authors).split('\n').map(s=>s.trim()).filter(Boolean),year:form.year?Number(form.year):null,sort_order:Number(form.sort_order)};const r=await fetch('/api/v1/admin/content',{method:editId?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw Error(j.error);setEditId(j.data.id);await load();setMsg('저장되었습니다. 게시 상태이면 홈페이지에 반영됩니다.');}catch(e){setFailed(true);setMsg(e instanceof Error?e.message:'저장 실패');}finally{setBusy(false)}}
async function remove(id:string){try{const r=await fetch('/api/v1/admin/content',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({type,id})});const j=await r.json();if(!r.ok)throw Error(j.error);await load();setConfirmId('');setMsg('공개 페이지에서 삭제되었습니다. 다시 게시하여 복원할 수 있습니다.');}catch(e){setFailed(true);setMsg(e instanceof Error?e.message:'삭제 실패')}}
function reset(){setFailed(false);setEditId('');setForm({...initial,category:initialCategory});setMsg('새 콘텐츠 작성');}
function input(key:string,label:string,props:Item={}){return <label>{label}<input className="field" value={form[key]??''} onChange={e=>field(key,e.target.value)} {...props}/></label>}
return <div className="editor-workspace"><section className="admin-box editor-form-panel"><h2>{editId?'선택한 항목 수정':'새 항목 작성'}</h2><div className="filterbar">{!focused&&<label>관리 항목<select value={type} onChange={e=>{setType(e.target.value);reset();setList([])}}><option value="posts">게시글</option><option value="pages">페이지 본문</option><option value="members">구성원</option><option value="publications">논문</option></select></label>}<button className="secondary-button" onClick={reset}>새로 작성</button></div><form onSubmit={save}>
{input('title',type==='members'?'이름':'제목',{required:true})}
{type==='pages'&&input('slug','페이지 위치 (예: about/greetings)',{required:true})}{type==='posts'&&<details className="editor-advanced"><summary>고급 설정 · 게시글 주소</summary>{input('slug','게시글 주소 (비우면 자동 생성)')}</details>}
{type==='pages'&&<>{input('lead','부제')}<label>기존 페이지 선택<select className="field" value={sections[form.slug]?form.slug:''} onChange={e=>{const slug=e.target.value;if(!slug)return;const found=list.find(it=>it.slug===slug);if(found)edit(found);else {setEditId('');setForm({...initial,slug,title:sections[slug].title,lead:sections[slug].lead,body:sections[slug].body});}}}><option value="">페이지 선택</option>{Object.entries(sections).map(([key,v])=><option key={key} value={key}>{v.title} ({key})</option>)}</select></label></>}
{type==='posts'&&<label>게시판<select className="field" value={form.category} onChange={e=>field('category',e.target.value)}>{[['notice','공지사항'],['news','연구실 소식'],['research','연구성과'],['academic','학술활동'],['events','행사'],...Object.entries(sections).map(([key,v])=>['page:'+key,v.title+' 게시판'])].map(([key,name])=><option value={key} key={key}>{name}</option>)}</select></label>}
{type==='members'&&<><div className="form-grid">{input('name_en','영문 이름')}<label>구분<select className="field" value={form.role} onChange={e=>field('role',e.target.value)}>{roles.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{input('email','이메일',{type:'email'})}{input('sort_order','같은 구분 내 표시 순서',{type:'number',min:0,max:10000})}</div>{input('scholar_author_id','Google Scholar user ID')}{input('photo_url','사진 URL / 업로드 경로')}<ImageUpload onBusyChange={setUploading} onUploaded={url=>field('photo_url',url)}/><p className="search-help">교수 이력은 소개 본문에 연구분야·학력·경력 등의 소제목으로 작성할 수 있습니다.</p></>}
{type!=='publications'&&(type==='posts'?<div className="compose-body"><h3>본문</h3><RichEditor value={form.body} onChange={v=>field('body',v)} disabled={busy}/></div>:<label>{type==='members'?'소개 / 이력':'본문'}<textarea className="field" rows={10} value={form.body} onChange={e=>field('body',e.target.value)}/></label>)}
{type==='publications'&&<><p className="search-help">제목만 입력해도 저장할 수 있습니다. 저자와 학술지 정보는 나중에 보완할 수 있습니다.</p><label>저자<textarea className="field" rows={2} placeholder="한 줄에 한 명씩 입력" value={form.authors} onChange={e=>field('authors',e.target.value)}/></label><div className="form-grid">{input('year','발행연도',{type:'number',min:1900,max:2100,placeholder:'예: 2026'})}{input('venue','학술지 / 학회',{placeholder:'학술지 이름'})}</div><details className="editor-advanced"><summary>원문 링크와 DOI 추가 (선택)</summary>{input('paper_url','논문 URL',{type:'url',placeholder:'https://…'})}{input('doi','DOI')}</details></>}
<PublishSwitch checked={form.status==='published'} onChange={v=>field('status',v?'published':'draft')} disabled={busy}/>
<div className="form-actions"><button className="primary" disabled={busy||loading||uploading}>{busy?'저장 중…':editId?'수정 저장':form.status==='published'?'게시하기':'임시저장'}</button><button type="button" className="secondary-button" disabled={busy} onClick={reset}>취소</button><p className={"form-feedback "+(failed?"error":"")} role="status" aria-live="polite">{msg}</p></div></form></section><section className="admin-box editor-list-panel"><div className="list-panel-heading"><h2>등록된 항목</h2><button className="secondary-button" onClick={load} disabled={loading}>새로고침</button></div><input className="field" value={search} onChange={e=>setSearch(e.target.value)} placeholder="이름 또는 제목으로 검색" aria-label="등록 항목 검색"/><p className="search-help">삭제는 공개 해제입니다. 임시저장 항목도 수정·재게시할 수 있습니다.</p>{list.filter(it=>it.slug!=='home/banner'&&String(it.title||it.name).toLowerCase().includes(search.toLowerCase())).map(it=><div className={"cms-row "+(it.id===editId?"selected":"")} key={it.id}><div><strong>{it.title||it.name}</strong><p className="search-help">{it.status||(it.is_visible?'공개':'비공개')} · {it.category||it.role||it.slug}</p></div><div><button className="secondary-button" onClick={()=>edit(it)}>수정</button> {confirmId===it.id?<><button className="danger-button" onClick={()=>remove(it.id)}>공개 해제 확인</button><button className="secondary-button" onClick={()=>setConfirmId('')}>취소</button></>:<button className="secondary-button" onClick={()=>setConfirmId(it.id)}>공개 해제</button>}</div></div>)}{loading?<p className="muted" role="status">목록을 불러오는 중…</p>:!list.length?<div className="empty">등록된 항목이 없습니다. 새 항목을 작성하세요.</div>:!list.some(it=>it.slug!=='home/banner'&&String(it.title||it.name).toLowerCase().includes(search.toLowerCase()))&&<div className="empty">검색 결과가 없습니다.</div>}</section></div>}
