'use client';
import {useState,useEffect} from 'react';import Link from 'next/link';import {useRouter} from 'next/navigation';import {useAccount} from './AccountProvider';import {isAdministrator} from '@/lib/permissions';
const groups=[['Postdoc','박사후연구원'],['PhD','박사과정'],['Masters','석사과정'],['Undergraduate','학부연구생']];
export default function OrganizationChart({people,leaderId}:{people:any[];leaderId:string}){
 const {account}=useAccount(),router=useRouter();const [editing,setEditing]=useState(false),[options,setOptions]=useState<any[]>([]),[selected,setSelected]=useState(leaderId),[busy,setBusy]=useState(false),[error,setError]=useState('');const leader=people.find(p=>p.id===leaderId);
 useEffect(()=>{if(!editing)return;fetch('/api/v1/admin/organization').then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error);setOptions(j.members||[]);setSelected(j.leaderId||'')}).catch(e=>setError(e.message))},[editing]);
 return <section className="organization-section" aria-label="연구실 조직도">{isAdministrator(account?.role)&&<div className="inline-edit-toolbar"><span>조직도 관리</span><button className="secondary-button" onClick={()=>{setError('');setEditing(!editing)}}>랩장 지정</button></div>}{editing&&<form className="organization-settings" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/v1/admin/organization',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({leaderId:selected})});const j=await r.json();if(!r.ok)throw Error(j.error);setEditing(false);router.refresh()}catch(e){setError(e instanceof Error?e.message:'저장 실패')}finally{setBusy(false)}}}><label>랩장<select className="field" value={selected} onChange={e=>setSelected(e.target.value)} disabled={busy}><option value="">미지정</option>{options.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="dialog-actions"><button type="button" className="secondary-button" disabled={busy} onClick={()=>setEditing(false)}>취소</button><button className="primary" disabled={busy}>{busy?'저장 중…':'저장'}</button></div>{error&&<p className="error" role="alert">{error}</p>}</form>}
 <div className="organization-tree"><div className="organization-root"><span className="kicker">랩장</span>{leader?<Link href={'/people/'+leader.id}>{leader.name}</Link>:<strong>미지정</strong>}</div><ul className="organization-groups">{groups.map(([role,label])=><li className="organization-group" key={role}><h3>{label}</h3><ul>{people.filter(p=>p.role===role&&p.id!==leaderId).map(p=><li key={p.id}><Link href={'/people/'+p.id}>{p.name}</Link></li>)}</ul>{!people.some(p=>p.role===role&&p.id!==leaderId)&&<p className="muted">등록된 구성원 없음</p>}</li>)}</ul></div></section>;
}
