import PublicImage from './PublicImage';
import DefaultArtwork from './DefaultArtwork';
import RichText from './RichText';import Link from 'next/link';import AdminToolbar from './AdminToolbar';
import {professor,memberGroups,groupRole} from '@/lib/professor';import {professorDetails} from '@/lib/professor-details';
export function ProfessorProfile({member=professor}:{member?:any}){const details=professorDetails(member.professor_details);return <section className="professor-profile"><div className="professor-top"><div className="professor-portrait">{(member.photo_url||professor.photo_url)?<PublicImage sizes="280px" priority src={member.photo_url||professor.photo_url} alt={member.name} width={280} height={350}/>:<DefaultArtwork src="/assets/brand/lab-mark.svg" alt="연구실 심볼"/>}</div><div><span className="kicker">PRINCIPAL INVESTIGATOR</span><h3>{member.name} <small>{member.name_en||'Kwangmin Lee'}</small></h3><p>{details.position}</p>{member.email&&<a href={'mailto:'+member.email}>{member.email}</a>}<p>{details.office}{details.phone&&' · '+details.phone}</p>{details.website&&<a className="secondary-button" href={details.website} target="_blank" rel="noopener noreferrer">교수 개인 홈페이지 ↗</a>}</div></div>{details.interests&&<div className="profile-section"><h3>연구 관심 분야</h3><div className="interest-tags">{details.interests.split('\n').filter(Boolean).map(x=><span className="pill" key={x}>{x}</span>)}</div></div>}{details.career&&<div className="profile-section"><h3>학력 및 주요 경력</h3><dl className="career-list">{details.career.split('\n').filter(Boolean).map((line,i)=>{const [date,...description]=line.split('|');return <div key={i}><dt>{description.length?date.trim():''}</dt><dd>{description.length?description.join('|').trim():date}</dd></div>})}</dl></div>}{member.bio&&member.bio!==professor.bio&&<div className="profile-section"><h3>소개</h3><RichText body={member.bio}/></div>}</section>}
export default function People({people}:{people:any[]}){
 const list=people.length?people:[professor],professors=list.filter(m=>groupRole(m.role)==='Professor'),currentGroups=memberGroups.filter(([role])=>!['Professor','Alumni'].includes(role)&&list.some(m=>groupRole(m.role)===role)),hasAlumni=list.some(m=>groupRole(m.role)==='Alumni');
 function group(role:string,label:string){return <section className="member-group" key={role}>{role!=='Alumni'&&<div className="member-group-heading"><h3>{label}</h3><span>{role==='Masters'?'Master’s Students':role==='PhD'?'Ph.D. Students':role==='Postdoc'?'Postdoctoral Researchers':role==='Researcher'?'Researchers':role==='Undergraduate'?'Undergraduate Researchers':role}</span></div>}<div className="member-cards">{list.filter(m=>groupRole(m.role)===role).map(m=><Link href={'/people/'+m.id} className="person" key={m.id}><div className="avatar">{m.photo_url?<PublicImage sizes="120px" src={m.photo_url} loading="lazy" decoding="async" alt={m.name} width={120} height={150}/>:m.name[0]}</div><div><h3>{m.name} {m.name_en&&<small>{m.name_en}</small>}</h3><p>{role==='Alumni'?(m.alumni_details?.current_affiliation||m.details?.current_affiliation||label):m.details?.department||label}</p>{role==='Alumni'&&(m.alumni_details?.current_position||m.details?.current_position)&&<p>{m.alumni_details?.current_position||m.details?.current_position}</p>}{m.email&&<p>{m.email}</p>}</div></Link>)}</div></section>}
 return <><section className="professors-section"><div className="team-section-heading"><h2>지도교수</h2><span className="muted">Principal Investigator</span></div>{professors.map(m=><AdminToolbar key={m.id} type="members" id={m.id==='professor'?'':m.id}><ProfessorProfile member={m}/></AdminToolbar>)}</section>{currentGroups.length>0&&<section className="research-team-section" aria-labelledby="lab-members-title"><div className="team-section-heading"><div><p className="kicker">LAB MEMBERS</p><h2 id="lab-members-title">연구실 구성원</h2></div><AdminToolbar type="members"/></div>{currentGroups.map(([role,label])=>group(role,label))}</section>}{hasAlumni&&<section className="alumni-section" aria-labelledby="alumni-title"><div className="team-section-heading"><h2 id="alumni-title">졸업생</h2><span className="muted">Alumni</span></div>{group('Alumni','졸업생')}</section>}</>;
}
