'use client';
import {useState} from 'react';import {useRouter} from 'next/navigation';import Link from 'next/link';
import {useAccount} from './AccountProvider';import {canWriteBoard} from '@/lib/permissions';import {boardOptions} from '@/lib/board-options';
import dynamic from 'next/dynamic';import PublishSwitch from './PublishSwitch';
const RichEditor=dynamic(()=>import('./RichEditor'),{ssr:false,loading:()=> <div className="rich-editor-loading" role="status">에디터를 불러오는 중…</div>});
export default function PostEditor({category,post,onDone,onCancel}:{category:string;post?:any;onDone?:(post:any)=>void;onCancel?:()=>void}){
 const {account}=useAccount();const [destination,setDestination]=useState(post?.category||category);
 const [title,setTitle]=useState(post?.title||''),[body,setBody]=useState(post?.body||''),[status,setStatus]=useState(post?.status||'published'),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[uploading,setUploading]=useState(false);const router=useRouter();const back=destination==='notice'?'/notice':destination.startsWith('page:')?'/'+destination.slice(5):'/news';
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg('');try{const r=await fetch('/api/board',{method:post?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:post?.id,title,body,category:destination,status})});const j=await r.json();if(!r.ok)throw Error(j.error);if(onDone){onDone(j.data);router.refresh();return;}router.push(status==='published'?destination==='notice'?'/notice/'+j.data.slug:destination.startsWith('page:')?back:'/news/'+j.data.slug:'/account#my-posts');router.refresh()}catch(e){setMsg(e instanceof Error?e.message:'저장하지 못했습니다.')}finally{setBusy(false)}}
 return <form className="editor-card compose-card" onSubmit={save}><div className="destination-picker"><span className="field-label">게시 위치</span><div className="destination-tabs" role="tablist" aria-label="게시할 페이지">{boardOptions.slice(0,5).filter(([key])=>canWriteBoard(account,key)).map(([key,label])=><button type="button" role="tab" aria-selected={destination===key} disabled={busy||uploading} key={key} onClick={()=>setDestination(key)}>{label}</button>)}{boardOptions.slice(5).some(([key])=>canWriteBoard(account,key))&&<button type="button" role="tab" aria-selected={destination.startsWith('page:')} disabled={busy||uploading} onClick={()=>setDestination(destination.startsWith('page:')?destination:boardOptions[5][0])}>페이지 게시판</button>}</div>{destination.startsWith('page:')&&<label>페이지 선택<select className="field" value={destination} disabled={busy||uploading} onChange={e=>setDestination(e.target.value)}>{boardOptions.slice(5).filter(([key])=>canWriteBoard(account,key)).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>}</div><p className="destination-hint">{boardOptions.find(([key])=>key===destination)?.[1]||destination}에 게시됩니다.</p><label htmlFor="post-title">제목</label><input id="post-title" className="field compose-title" required maxLength={250} disabled={busy} value={title} onChange={e=>setTitle(e.target.value)} placeholder="제목을 입력하세요"/><div className="compose-body"><h2>본문</h2><RichEditor value={body} onChange={setBody} disabled={busy} category={destination} onUploadBusy={setUploading}/></div><PublishSwitch checked={status==='published'} onChange={v=>setStatus(v?'published':'draft')} disabled={busy}/>{msg&&<p className="error" role="alert">{msg}</p>}<div className="compose-actions"><Link className="secondary-button" href={back} aria-disabled={busy||uploading} onClick={e=>{if(busy||uploading)e.preventDefault();else if(onCancel){e.preventDefault();onCancel()}}}>취소</Link><button className="primary" disabled={busy||uploading}>{busy?'저장 중…':status==='draft'?'임시저장':post?'수정 완료':'게시하기'}</button></div></form>;
}
