'use client';
import {useState} from 'react';import {useRouter} from 'next/navigation';import Link from 'next/link';
import dynamic from 'next/dynamic';import PublishSwitch from './PublishSwitch';
const RichEditor=dynamic(()=>import('./RichEditor'),{ssr:false,loading:()=> <div className="rich-editor-loading" role="status">에디터를 불러오는 중…</div>});
export default function PostEditor({category,post,onDone,onCancel}:{category:string;post?:any;onDone?:(post:any)=>void;onCancel?:()=>void}){
 const [title,setTitle]=useState(post?.title||''),[body,setBody]=useState(post?.body||''),[status,setStatus]=useState(post?.status||'published'),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[uploading,setUploading]=useState(false);const router=useRouter();const back=category==='notice'?'/notice':category.startsWith('page:')?'/'+category.slice(5):'/news';
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg('');try{const r=await fetch('/api/board',{method:post?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:post?.id,title,body,category,status})});const j=await r.json();if(!r.ok)throw Error(j.error);if(onDone){onDone(j.data);router.refresh();return;}router.push(status==='published'?category==='notice'?'/notice/'+j.data.slug:category.startsWith('page:')?back:'/news/'+j.data.slug:'/account#my-posts');router.refresh()}catch(e){setMsg(e instanceof Error?e.message:'저장하지 못했습니다.')}finally{setBusy(false)}}
 return <form className="editor-card compose-card" onSubmit={save}><label htmlFor="post-title">제목</label><input id="post-title" className="field compose-title" required maxLength={250} disabled={busy} value={title} onChange={e=>setTitle(e.target.value)} placeholder="제목을 입력하세요"/><div className="compose-body"><h2>본문</h2><RichEditor value={body} onChange={setBody} disabled={busy} category={category} onUploadBusy={setUploading}/></div><PublishSwitch checked={status==='published'} onChange={v=>setStatus(v?'published':'draft')} disabled={busy}/>{msg&&<p className="error" role="alert">{msg}</p>}<div className="compose-actions"><Link className="secondary-button" href={back} aria-disabled={busy||uploading} onClick={e=>{if(busy||uploading)e.preventDefault();else if(onCancel){e.preventDefault();onCancel()}}}>취소</Link><button className="primary" disabled={busy||uploading}>{busy?'저장 중…':status==='draft'?'임시저장':post?'수정 완료':'게시하기'}</button></div></form>;
}
