'use client';
import {useState,useEffect} from 'react';import Link from 'next/link';import {useRouter} from 'next/navigation';import {useAccount} from './AccountProvider';import {isAdministrator} from '@/lib/permissions';import ConfirmDelete from './ConfirmDelete';import {postDate} from '@/lib/post-metadata';
export default function PostList({posts,gallery=false,base='news'}:{posts:any[];gallery?:boolean;base?:string}){
 const {account}=useAccount(),router=useRouter();const admin=isAdministrator(account?.role);const [selected,setSelected]=useState<string[]>([]),[confirming,setConfirming]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setSelected([]);setConfirming(false)},[posts]);
 async function remove(){setBusy(true);setError('');try{let completed=0;for(const id of selected){const r=await fetch('/api/board',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})});const j=await r.json();if(!r.ok)throw Error((completed?completed+'개 삭제 후 ':'')+(j.error||'삭제 실패'));completed++;setSelected(ids=>ids.filter(item=>item!==id))}setSelected([]);setConfirming(false);router.refresh()}catch(e){setError(e instanceof Error?e.message:'삭제 실패');router.refresh()}finally{setBusy(false)}}
 const selection=(post:any)=>admin&&<input type="checkbox" checked={selected.includes(post.id)} aria-label={post.title+' 선택'} onChange={e=>setSelected(ids=>e.target.checked?[...ids,post.id]:ids.filter(id=>id!==post.id))}/>;
 return <>{!posts.length?<div className="empty">등록된 게시글이 없습니다.</div>:gallery?<div className="event-gallery">{posts.map(post=><article className="event-card" key={post.id}>{admin&&<label className="gallery-select">{selection(post)} 선택</label>}<Link href={'/'+base+'/'+post.slug}>{post.cover_image?<img src={post.cover_image} alt={post.title} width={640} height={400} loading="lazy" decoding="async"/>:<div className="event-image-placeholder">행사 사진</div>}<div className="event-card-body"><span className="post-number">#{post.post_number}</span><h3>{post.title}</h3><p>{post.author_name} · {postDate(post.created_at)}</p><small>수정 {postDate(post.updated_at)}</small></div></Link></article>)}</div>:<div className="board-table-wrap"><table className="list-table board-table"><thead><tr>{admin&&<th><input type="checkbox" aria-label="게시글 전체 선택" checked={selected.length===posts.length&&posts.length>0} onChange={e=>setSelected(e.target.checked?posts.map(p=>p.id):[])}/></th>}<th>번호</th><th>제목</th><th>작성자</th><th>최초 등록일</th><th>수정일</th></tr></thead><tbody>{posts.map(post=><tr key={post.id}>{admin&&<td>{selection(post)}</td>}<td className="post-number">{post.post_number}</td><td><Link href={'/'+base+'/'+post.slug}>{post.title}</Link></td><td>{post.author_name}</td><td>{postDate(post.created_at)}</td><td>{postDate(post.updated_at)}</td></tr>)}</tbody></table></div>}{admin&&selected.length>0&&<div className="selection-actions"><span>{selected.length}개 선택</span><button className="danger-button" onClick={()=>{setError('');setConfirming(true)}}>선택한 게시글 삭제</button></div>}{confirming&&<ConfirmDelete title={selected.length+'개 게시글을 삭제할까요?'} description="선택한 게시글은 복원할 수 없습니다." busy={busy} error={error} onConfirm={remove} onCancel={()=>setConfirming(false)}/>}</>;
}
