'use client';
import {useEditor,EditorContent} from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import Placeholder from '@tiptap/extension-placeholder';
import {useEffect,useState} from 'react';
import {Bold,Italic,Underline,List,ListOrdered,Quote,Undo,Redo,Link as LinkIcon,Heading2,Heading3,RemoveFormatting} from 'lucide-react';
const prefix='<!--bsl-richtext-->';
function content(value:string){if(value.startsWith(prefix))return value.slice(prefix.length);return value.split('\n').map(s=>'<p>'+s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')+'</p>').join('');}
export default function RichEditor({value,onChange,disabled=false}:{value:string;onChange:(s:string)=>void;disabled?:boolean}){
 const [showLink,setShowLink]=useState(false),[href,setHref]=useState(''),[linkError,setLinkError]=useState('');
 const editor=useEditor({extensions:[StarterKit.configure({heading:{levels:[2,3]},link:{openOnClick:false}}),Placeholder.configure({placeholder:'내용을 작성하세요…'})],immediatelyRender:false,shouldRerenderOnTransaction:true,content:content(value),editable:!disabled,onUpdate:({editor})=>onChange(prefix+editor.getHTML()),editorProps:{attributes:{'aria-label':'본문','role':'textbox','aria-multiline':'true'}}});
 useEffect(()=>{if(editor&&prefix+editor.getHTML()!==value&&editor.getText()!==value)editor.commands.setContent(content(value),{emitUpdate:false})},[value,editor]);
 useEffect(()=>{editor?.setEditable(!disabled)},[disabled,editor]);
 if(!editor)return <div className="rich-editor-loading" role="status">에디터를 준비하고 있습니다…</div>;
 const controls=[{label:'굵게',Icon:Bold,active:editor.isActive('bold'),run:()=>editor.chain().focus().toggleBold().run()},{label:'기울임',Icon:Italic,active:editor.isActive('italic'),run:()=>editor.chain().focus().toggleItalic().run()},{label:'밑줄',Icon:Underline,active:editor.isActive('underline'),run:()=>editor.chain().focus().toggleUnderline().run()},{label:'큰 소제목',Icon:Heading2,active:editor.isActive('heading',{level:2}),run:()=>editor.chain().focus().toggleHeading({level:2}).run()},{label:'작은 소제목',Icon:Heading3,active:editor.isActive('heading',{level:3}),run:()=>editor.chain().focus().toggleHeading({level:3}).run()},{label:'글머리 목록',Icon:List,active:editor.isActive('bulletList'),run:()=>editor.chain().focus().toggleBulletList().run()},{label:'번호 목록',Icon:ListOrdered,active:editor.isActive('orderedList'),run:()=>editor.chain().focus().toggleOrderedList().run()},{label:'인용문',Icon:Quote,active:editor.isActive('blockquote'),run:()=>editor.chain().focus().toggleBlockquote().run()},{label:'서식 지우기',Icon:RemoveFormatting,active:false,run:()=>editor.chain().focus().unsetAllMarks().clearNodes().run()}];
 return <div className="rich-editor"><div className="editor-toolbar" role="toolbar" aria-label="본문 서식">{controls.map(({label,Icon,active,run})=><button key={label} type="button" title={label} aria-label={label} aria-pressed={active} disabled={disabled} onClick={run}><Icon size={18}/></button>)}<button type="button" title="링크" aria-label="링크" aria-pressed={editor.isActive('link')} disabled={disabled} onClick={()=>{setHref(editor.getAttributes('link').href||'');setShowLink(!showLink);setLinkError('')}}><LinkIcon size={18}/></button><span className="toolbar-divider"/><button type="button" title="실행 취소" aria-label="실행 취소" disabled={disabled||!editor.can().undo()} onClick={()=>editor.chain().focus().undo().run()}><Undo size={18}/></button><button type="button" title="다시 실행" aria-label="다시 실행" disabled={disabled||!editor.can().redo()} onClick={()=>editor.chain().focus().redo().run()}><Redo size={18}/></button></div>{showLink&&<div className="editor-link-panel"><label>링크 주소<input className="field" placeholder="https://…" value={href} onChange={e=>setHref(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')e.preventDefault()}}/></label><button type="button" className="secondary-button" onClick={()=>{if(!/^(https?:\/\/|mailto:)/i.test(href)){setLinkError('http, https 또는 이메일 주소를 입력하세요.');return;}editor.chain().focus().extendMarkRange('link').setLink({href}).run();setShowLink(false)}}>적용</button><button type="button" className="nav-button" onClick={()=>{editor.chain().focus().unsetLink().run();setShowLink(false)}}>링크 제거</button>{linkError&&<p className="error" role="alert">{linkError}</p>}</div>}<EditorContent editor={editor}/><div className="editor-footer">{editor.getText().length.toLocaleString()}자</div></div>;
}
