'use client';
import {useEffect,useState} from 'react';import PublishSwitch from './PublishSwitch';
export default function ScholarManager({onImported}:{onImported?:()=>void}){
const [author,setAuthor]=useState(''),[query,setQuery]=useState(''),[memberId,setMemberId]=useState(''),[members,setMembers]=useState<any[]>([]),[articles,setArticles]=useState<any[]>([]),[selected,setSelected]=useState<string[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[publish,setPublish]=useState(false);
useEffect(()=>{fetch('/api/v1/admin/content?type=members').then(r=>r.json()).then(j=>{if(j.error)throw Error(j.error);const list=j.data||[];setMembers(list);const first=list.find((m:any)=>m.role==='Professor'||m.role==='Principal Investigator')||list[0];if(first){setMemberId(first.id);setAuthor(first.scholar_author_id||'')}}).catch(()=>setMessage('구성원 정보를 불러오지 못했습니다. 페이지를 다시 열어주세요.'))},[]);
async function request(action:string,payload:any){const r=await fetch('/api/v1/admin/scholar/'+action,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw Error(j.error||'논문 정보를 불러오지 못했습니다.');return j}
async function load(search=false){setBusy(true);setMessage('');try{const j=await request(search?'search':'preview',search?{q:query}:{author_url:author,member_id:memberId,connect:true});setArticles(j.articles||[]);setSelected([]);setMessage(`${j.articles?.length||0}개 논문을 찾았습니다. 추가할 논문을 선택해주세요.`)}catch(e){setMessage(e instanceof Error?e.message:'조회 실패')}finally{setBusy(false)}}
async function importPapers(){setBusy(true);setMessage('');try{const j=await request('import',{member_id:memberId,articles:articles.filter(a=>selected.includes(a.source_id)),status:publish?'published':'draft'});setMessage(`${j.imported}개 논문을 추가했습니다. 이미 등록된 논문의 공개 상태는 유지됩니다.`);setSelected([]);onImported?.()}catch(e){setMessage(e instanceof Error?e.message:'추가하지 못했습니다.')}finally{setBusy(false)}}
return <section className="admin-box"><h2>Scholar에서 논문 가져오기</h2><p className="muted">프로필 조회 → 논문 선택 → 추가, 세 단계로 등록합니다.</p><div className="form-grid"><label>저자<select className="field" disabled={busy} value={memberId} onChange={e=>{setMemberId(e.target.value);setAuthor(members.find(m=>m.id===e.target.value)?.scholar_author_id||'');setArticles([]);setSelected([])}}><option value="">구성원 선택</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Google Scholar 프로필<input className="field" disabled={busy} value={author} onChange={e=>setAuthor(e.target.value)} placeholder="프로필 링크 또는 user ID"/></label></div><button className="primary" disabled={busy||!author||!memberId} onClick={()=>load()}>{busy?'처리 중…':'프로필 연결하고 논문 불러오기'}</button><details className="editor-advanced"><summary>프로필 대신 논문 제목으로 검색</summary><label>논문 제목 / 키워드<input className="field" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="secondary-button" disabled={busy||query.trim().length<2} onClick={()=>load(true)}>논문 검색</button></details>{!!articles.length&&<><div className="scholar-selection"><strong>선택 {selected.length} / {articles.length}</strong><button className="secondary-button" disabled={busy} onClick={()=>setSelected(selected.length===articles.length?[]:articles.map(a=>a.source_id))}>{selected.length===articles.length?'선택 해제':'전체 선택'}</button></div><div className="scholar-results">{articles.map(a=><label className="scholar-result" key={a.source_id}><input type="checkbox" disabled={busy} checked={selected.includes(a.source_id)} onChange={e=>setSelected(s=>e.target.checked?[...s,a.source_id]:s.filter(id=>id!==a.source_id))}/><span><strong>{a.title}</strong><small>{(a.authors||[]).join(', ')} · {a.year||'연도 미상'} · {a.venue||''}</small></span></label>)}</div><PublishSwitch checked={publish} disabled={busy} onChange={setPublish}/><div className="scholar-actions"><button className="primary" disabled={busy||!selected.length||!memberId} onClick={importPapers}>{busy?'추가 중…':`선택한 논문 ${selected.length}개 추가`}</button></div></>}{message&&<p className="form-feedback" role="status" aria-live="polite" style={{marginTop:20}}>{message}</p>}{!members.length&&<p className="search-help">연결할 구성원이 없다면 직접 입력으로 논문을 등록할 수 있습니다.</p>}</section>;
}
