import {boardPage,postNumbers} from './board-pagination';
import {postMetadata} from './post-metadata';
import {unstable_cache} from 'next/cache';
import { publicDb } from './supabase';
export const publishedPosts=unstable_cache(async function publishedPosts(category?:string,includeBody=false,limit=30){const db=publicDb();if(!db)return [];let q=db.from('posts').select(includeBody?'*':'id,title,slug,category,excerpt,published_at,created_at,author_id').eq('status','published').order('published_at',{ascending:false}).limit(limit);if(category)q=q.eq('category',category);const {data}=await q;return (data||[]).map(postMetadata)},['publishedPosts'],{revalidate:3600,tags:['lab-public']});
export const publishedPapers=unstable_cache(async function publishedPapers(){const db=publicDb();if(!db)return [];const {data}=await db.from('publications').select('id,title,authors,year,venue,doi,paper_url,citation_count').eq('status','published').order('year',{ascending:false}).limit(100);return data||[]},['publishedPapers'],{revalidate:3600,tags:['lab-public']});
export const members=unstable_cache(async function members(){const db=publicDb();if(!db)return [];const {data}=await db.from('members').select('id,user_id,name,name_en,role,bio,email,photo_url,scholar_author_id').eq('is_visible',true).order('sort_order');const {data:details}=await db.from('pages').select('slug,body').like('slug','settings/%').eq('status','published');const byId=new Map((details||[]).map(p=>{let value={};try{value=JSON.parse(p.body||'{}')}catch{}return [p.slug,value]}));return (data||[]).map(p=>({...p,details:byId.get('settings/member/'+p.id)||{},professor_details:byId.get('settings/professor/'+p.id)}))},['members'],{revalidate:3600,tags:['lab-public']});
export const page=unstable_cache(async function page(slug:string){const db=publicDb();if(!db)return null;const {data}=await db.from('pages').select('title,lead,body').eq('slug',slug).eq('status','published').maybeSingle();return data},['page'],{revalidate:3600,tags:['lab-public']});

export const publishedPost=unstable_cache(async function publishedPost(slug:string,category?:string){const db=publicDb();if(!db)return null;let q=db.from('posts').select('*').eq('status','published').eq('slug',slug);if(category)q=q.eq('category',category);const {data}=await q.maybeSingle();if(!data)return null;const numbers=await publishedPostNumbers();return {...postMetadata(data),post_number:numbers[data.id]||1}},['publishedPost'],{revalidate:3600,tags:['lab-public']});

export const publishedBoard=unstable_cache(async function publishedBoard(category:string,requestedPage:number,size:number,includeBody=false){const db=publicDb();if(!db)return {posts:[],total:0,page:1};const apply=(query:any)=>category==='all-news'?query.in('category',['news','research','academic','events']):query.eq('category',category);const {count}=await apply(db.from('posts').select('id',{count:'exact',head:true}).eq('status','published'));const total=count||0,current=boardPage(requestedPage,total,size),offset=(current-1)*size;const {data}=await apply(db.from('posts').select(includeBody?'*':'id,title,slug,category,excerpt,published_at,created_at,author_id').eq('status','published')).order('created_at',{ascending:false}).order('id',{ascending:false}).range(offset,offset+size-1);const numbers=await publishedPostNumbers();return {posts:(data||[]).map((post:any)=>({...postMetadata(post),post_number:numbers[post.id]})),total,page:current}},['publishedBoard'],{revalidate:3600,tags:['lab-public']});

const publishedPostNumbers=unstable_cache(async function publishedPostNumbers(){const db=publicDb();if(!db)return {};const posts:any[]=[];for(let offset=0;;offset+=1000){const {data,error}=await db.from('posts').select('id,category').eq('status','published').order('created_at',{ascending:true}).order('id',{ascending:true}).range(offset,offset+999);if(error)throw Error('게시글 순번을 불러오지 못했습니다.');posts.push(...(data||[]));if(!data||data.length<1000)break}return postNumbers(posts)},['publishedPostNumbers'],{revalidate:3600,tags:['lab-public']});
