import {z} from 'zod';
export function extractAuthorId(input:string){if(/^[A-Za-z0-9_-]{4,40}$/.test(input))return input;try{const u=new URL(input);if(u.hostname!=='scholar.google.com'&&u.hostname!=='scholar.google.co.kr')return null;const id=u.searchParams.get('user');return id&&/^[A-Za-z0-9_-]{4,40}$/.test(id)?id:null}catch{return null}}
export const articleSchema=z.object({summary:z.string().max(16000).optional(),source_id:z.string().min(1).max(200),title:z.string().min(1).max(1000),authors:z.array(z.string()).max(100).default([]),year:z.number().int().min(1800).max(2200).nullable().optional(),venue:z.string().max(1000).nullable().optional(),paper_url:z.string().url().nullable().optional(),citation_count:z.number().int().nonnegative().optional(),source:z.enum(['author','search'])});
export type ScholarArticle=z.infer<typeof articleSchema>;
export async function serp(params:Record<string,string>){const key=process.env.SERPAPI_API_KEY;if(!key)throw Error('SERPAPI_API_KEY not configured');const url=new URL('https://serpapi.com/search.json');Object.entries({...params,api_key:key}).forEach(([k,v])=>url.searchParams.set(k,v));const res=await fetch(url.toString(),{cache:'no-store',signal:AbortSignal.timeout(25000)});if(!res.ok)throw Error('Scholar upstream error: '+res.status);const json=await res.json();if(json.error)throw Error('Scholar service error');return json}
export function parseAuthorArticles(json:any):ScholarArticle[]{return (json.articles||[]).map((a:any)=>({source_id:String(a.citation_id||''),title:a.title||'',authors:String(a.authors||'').split(',').map((s:string)=>s.trim()).filter(Boolean),year:a.year?Number(a.year):null,venue:a.publication||null,paper_url:a.link||null,citation_count:Number(a.cited_by?.value||0),source:'author' as const})).filter((a:any)=>a.source_id&&a.title)}
export function parseSearchArticles(json:any):ScholarArticle[]{return (json.organic_results||[]).map((a:any)=>({summary:String(a.snippet||'').slice(0,16000),source_id:String(a.result_id||''),title:a.title||'',authors:(a.publication_info?.authors||[]).map((x:any)=>x.name).filter(Boolean),year:Number(a.publication_info?.summary?.match(/\b(?:19|20)\d{2}\b/)?.[0])||null,venue:a.publication_info?.summary||null,paper_url:a.link||null,citation_count:Number(a.inline_links?.cited_by?.total||0),source:'search' as const})).filter((a:any)=>a.source_id&&a.title)}

export function citationDetails(json:any){const citation=json?.citation||{};return {summary:typeof citation.description==='string'?citation.description.slice(0,16000):'',venue:typeof citation.journal==='string'?citation.journal:typeof citation.book==='string'?citation.book:''}}
