import Link from 'next/link';import {notFound} from 'next/navigation';import PageHero from '@/components/PageHero';import {nav,sections,site} from '@/lib/content';import {publishedPosts,publishedPapers,members,page} from '@/lib/data';
export const revalidate=60;
export default async function GenericPage({params,searchParams}:{params:Promise<{slug:string[]}>;searchParams:Promise<{q?:string;year?:string}>}){const {slug}=await params;const qs=await searchParams;const path=slug.join('/');const section=sections[path];let title=section?.title||({people:'구성원',publications:'논문',notice:'공지사항',news:'연구실 소식',location:'오시는 길'} as Record<string,string>)[path];const postBase=path.startsWith('notice/')?'notice':path.startsWith('news/')?'news':null;
const isPosts=['notice','news'].includes(path)||['news/research','news/academic','news/events'].includes(path);const postType=path==='notice'?'notice':path==='news/research'?'research':path==='news/academic'?'academic':path==='news/events'?'events':'news';
let post:any=null;if(postBase){const posts=await publishedPosts(postBase);post=posts.find((p:any)=>p.slug===slug[1]);if(!post)notFound();title=post.title}
if(!title && !postBase && !path.startsWith('people/') && !path.startsWith('publications/'))notFound();
const active=nav.find(n=>path.startsWith(n.href.slice(1).split('/')[0])||n.links.some(l=>l[1]==='/'+path));const custom=section?await page(path):null;const content=custom||section;
const people=path==='people'||path.startsWith('people/')?await members():[];const papers=path==='publications'||path.startsWith('publications/')?await publishedPapers():[];
let member:any=null;if(path.startsWith('people/')){member=people.find((m:any)=>m.id===slug[1]);if(!member)notFound();title=member.name}
let paper:any=null;if(path.startsWith('publications/')){paper=papers.find((p:any)=>p.id===slug[1]);if(!paper)notFound();title=paper.title}
const posts=isPosts?await publishedPosts(postType):[];
return <main><PageHero title={title||'연구실'}/><div className="container body-grid"><aside className="side-nav">{(active?.links?.length?active.links:[[title||'소개','/'+path]]).map(([name,href])=><Link key={href} href={href}>{name}</Link>)}</aside><article className="content-panel"><h2 className="content-heading">{title}</h2>{content&&<><p className="lead">{content.lead}</p><p className="prose">{content.body}</p></>}
{path==='people'&&<>{people.length?people.map((m:any)=><Link href={'/people/'+m.id} className="person" key={m.id}><div className="avatar">{m.photo_url?<img src={m.photo_url} alt={m.name} width="98" height="116" style={{objectFit:'cover'}}/>:m.name[0]}</div><div><span className="pill">{m.role}</span><h3>{m.name} {m.name_en&&<small>({m.name_en})</small>}</h3><p>{m.bio||'연구실 구성원'}</p><p>{m.email}</p></div></Link>):<><div className="person"><div className="avatar">이</div><div><span className="pill">Principal Investigator</span><h3>이광민 (Kwangmin Lee)</h3><p>전남대학교 통계학과 · 조교수</p><p>{site.email}</p></div></div><div className="notice">다른 구성원은 관리자에서 확인된 정보로 등록해주세요.</div></>}</>}
{member&&<><p className="lead">{member.name_en}</p><p className="prose">{member.role}<br/>{member.bio}<br/>{member.email}</p>{member.scholar_author_id&&<a className="more" target="_blank" rel="noopener noreferrer" href={'https://scholar.google.com/citations?user='+encodeURIComponent(member.scholar_author_id)}>Google Scholar ↗</a>}</>}
{path==='publications'&&<><form className="filterbar" action="/publications"><input name="q" placeholder="논문 제목 또는 저자 검색" defaultValue={qs.q||''}/><input name="year" placeholder="연도 (예: 2025)" defaultValue={qs.year||''}/><button className="primary">검색</button></form>{papers.filter((p:any)=>(!qs.q||[p.title,...(p.authors||[])].join(' ').toLowerCase().includes(qs.q.toLowerCase()))&&(!qs.year||String(p.year)===qs.year)).map((p:any)=><div className="paper" key={p.id}><Link href={'/publications/'+p.id}><h3>{p.title}</h3></Link><p>{(p.authors||[]).join(', ')} · {p.venue||'Publication'} · {p.year||'연도 미상'}</p><p>인용 {p.citation_count??'—'}회 {p.doi&&<> · DOI {p.doi}</>}</p></div>)}{papers.length===0&&<div className="empty">논문이 아직 등록되지 않았습니다. 관리자에서 Scholar 논문을 연동할 수 있습니다.</div>}</>}
{paper&&<><p className="lead">{paper.title}</p><p className="prose">{(paper.authors||[]).join(', ')}<br/>{paper.venue} ({paper.year})<br/>DOI: {paper.doi||'미등록'}</p>{paper.paper_url&&<a href={paper.paper_url} target="_blank" rel="noopener noreferrer" className="more">논문 원문 보기 ↗</a>}</>}
{isPosts&&<>{posts.length?<table className="list-table"><thead><tr><th>제목</th><th>등록일</th></tr></thead><tbody>{posts.map((p:any)=><tr key={p.id}><td><Link href={'/'+(path==='notice'?'notice':'news')+'/'+p.slug}>{p.title}</Link></td><td>{p.published_at?.slice(0,10)}</td></tr>)}</tbody></table>:<div className="empty">등록된 게시글이 없습니다.</div>}</>}
{post&&<><p className="search-help">게시일: {post.published_at?.slice(0,10)||'—'}</p><p className="prose">{post.body}</p><Link href={'/'+postBase} className="more">목록으로 ←</Link></>}
{path==='location'&&<><p className="lead">전남대학교 자연과학대학</p><div className="location-card"><h3>{site.address}</h3><p>{site.room}</p><p>TEL {site.phone} / EMAIL {site.email}</p><a href="https://map.naver.com/p/search/%EC%A0%84%EB%82%A8%EB%8C%80%ED%95%99%EA%B5%90%20%EC%9E%90%EC%97%B0%EA%B3%BC%ED%95%99%EB%8C%80%ED%95%99%201%ED%98%B8%EA%B4%80" target="_blank" rel="noopener noreferrer" className="more">지도에서 보기 ↗</a></div></>}
{path.startsWith('support/')&&<p className="search-help">파일 첨부/다운로드 관리 기능은 관리자 업로드 기능에서 지원합니다.</p>}
</article></div></main>}
