import RichText from '@/components/RichText';import PublicationsList from '@/components/PublicationsList';
import Link from 'next/link';import {BoardWrite,BoardActions} from '@/components/BoardControls';import AdminToolbar from '@/components/AdminToolbar';import People,{ProfessorProfile} from '@/components/People';import {notFound} from 'next/navigation';import PageHero from '@/components/PageHero';import {nav,sections,site} from '@/lib/content';import {publishedPosts,publishedPost,publishedPapers,members,page} from '@/lib/data';
export const revalidate=3600;
export const dynamic='force-static';
export async function generateStaticParams(){return [...Object.keys(sections),'people','publications','notice','news','location'].map(path=>({slug:path.split('/')}));}

export default async function GenericPage({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;const path=slug.join('/');const section=sections[path];let title=section?.title||({people:'구성원',publications:'논문',notice:'공지사항',news:'연구실 소식',location:'오시는 길'} as Record<string,string>)[path];const postBase=path.startsWith('notice/')?'notice':path.startsWith('news/')?'news':null;
const isPosts=['notice','news'].includes(path)||['news/research','news/academic','news/events'].includes(path);const postType=path==='notice'?'notice':path==='news/research'?'research':path==='news/academic'?'academic':path==='news/events'?'events':'news';
let post:any=null;if(postBase&&!isPosts){post=await publishedPost(slug[1],postBase==='notice'?'notice':undefined);if(!post)notFound();title=post.title}
if(!title && !postBase && !path.startsWith('people/') && !path.startsWith('publications/'))notFound();
const active=nav.find(n=>path.startsWith(n.href.slice(1).split('/')[0])||n.links.some(l=>l[1]==='/'+path));const [custom,people,papers]=await Promise.all([section?page(path):null,path==='people'||path.startsWith('people/')?members():[],path==='publications'||path.startsWith('publications/')?publishedPapers():[]]);const content=custom||section;
let member:any=null;if(path.startsWith('people/')){member=people.find((m:any)=>m.id===slug[1]);if(!member)notFound();title=member.name}
let paper:any=null;if(path.startsWith('publications/')){paper=papers.find((p:any)=>p.id===slug[1]);if(!paper)notFound();title=paper.title}
const posts=isPosts?(await publishedPosts(path==='news'?undefined:postType)).filter((p:any)=>path!=='news'||['news','research','academic','events'].includes(p.category)):[];const pagePosts=section&&!isPosts?await publishedPosts('page:'+path,true):[];
return <main><PageHero title={title||'연구실'}/><div className="container body-grid"><aside className="side-nav">{(active?.links?.length?active.links:[[title||'소개','/'+path]]).map(([name,href])=><Link key={href} href={href}>{name}</Link>)}</aside><article className="content-panel"><AdminToolbar type={member?"members":paper?"publications":post||isPosts?"posts":path==="people"?"members":path==="publications"?"publications":"pages"} slug={section&&!isPosts?path:""} category={post?.category||postType} id={member?.id||paper?.id||post?.id||""}/><h2 className="content-heading">{title}</h2>{content&&<><p className="lead">{content.lead}</p><p className="prose">{content.body}</p></>}
{path==='people'&&<People people={people}/>}
{member&&member.name==='이광민'?<ProfessorProfile member={member}/>:member&&<><p className="lead">{member.name_en}</p><p className="prose">{member.role}<br/>{member.bio}<br/>{member.email}</p>{member.scholar_author_id&&<a className="more" target="_blank" rel="noopener noreferrer" href={'https://scholar.google.com/citations?user='+encodeURIComponent(member.scholar_author_id)}>Google Scholar ↗</a>}</>}
{path==='publications'&&<PublicationsList papers={papers}/> }
{paper&&<><p className="lead">{paper.title}</p><p className="prose">{(paper.authors||[]).join(', ')}<br/>{paper.venue} ({paper.year})<br/>DOI: {paper.doi||'미등록'}</p>{paper.paper_url&&<a href={paper.paper_url} target="_blank" rel="noopener noreferrer" className="more">논문 원문 보기 ↗</a>}</>}
{isPosts&&<><BoardWrite category={postType}/>{posts.length?<table className="list-table"><thead><tr><th>제목</th><th>등록일</th><th>관리</th></tr></thead><tbody>{posts.map((p:any)=><tr key={p.id}><td><Link href={'/'+(path==='notice'?'notice':'news')+'/'+p.slug}>{p.title}</Link></td><td>{p.published_at?.slice(0,10)}</td><td><BoardActions post={{id:p.id,category:p.category,author_id:p.author_id}}/></td></tr>)}</tbody></table>:<div className="empty">등록된 게시글이 없습니다.</div>}</>}
{post&&<><BoardActions post={{id:post.id,category:post.category,author_id:post.author_id}}/><p className="search-help">게시일: {post.published_at?.slice(0,10)||'—'}</p><RichText body={post.body||''}/><Link href={'/'+postBase} className="more">목록으로 ←</Link></>}
{path==='location'&&<><p className="lead">전남대학교 자연과학대학</p><div className="location-card"><h3>{site.address}</h3><p>{site.room}</p><p>TEL {site.phone} / EMAIL {site.email}</p><a href="https://map.naver.com/p/search/%EC%A0%84%EB%82%A8%EB%8C%80%ED%95%99%EA%B5%90%20%EC%9E%90%EC%97%B0%EA%B3%BC%ED%95%99%EB%8C%80%ED%95%99%201%ED%98%B8%EA%B4%80" target="_blank" rel="noopener noreferrer" className="more">지도에서 보기 ↗</a></div></>}
{section&&!isPosts&&<section className="page-board"><div className="section-top"><h3>게시글</h3><BoardWrite category={'page:'+path}/></div>{pagePosts.map((p:any)=><article className="paper" key={p.id}><BoardActions post={{id:p.id,category:p.category,author_id:p.author_id}}/><h3>{p.title}</h3><p className="search-help">{p.published_at?.slice(0,10)}</p><RichText body={p.body||''}/></article>)}</section>}
{path.startsWith('support/')&&<p className="search-help">파일 첨부/다운로드 관리 기능은 관리자 업로드 기능에서 지원합니다.</p>}
</article></div></main>}
