'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {defaultTheme,readTheme,themeFields,themePresets,themeVariables,themeWarnings} from '@/lib/theme';
import {loadTheme,saveTheme} from '../api/theme-client';
export default function ThemeEditor(){
 const router=useRouter();const [form,setForm]=useState(defaultTheme),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;loadTheme().then(data=>{if(active){setForm(readTheme(JSON.stringify(data)));setLoading(false)}}).catch(e=>{if(active){setError(true);setMessage(e.message)}});return()=>{active=false}},[]);
 const warnings=themeWarnings(form);
 return <section className="admin-box"><h2>사이트 색상</h2><p className="muted">추천 테마를 선택하거나 공통 색상을 조절하세요. 저장 전 변경은 아래 미리보기에만 적용됩니다.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');setError(false);try{await saveTheme(form);router.refresh();setMessage('사이트 디자인을 저장했습니다.')}catch(e){setError(true);setMessage(e instanceof Error?e.message:'저장 실패')}finally{setBusy(false)}}}><fieldset className="plain-fieldset" disabled={loading||busy}><div className="theme-presets">{themePresets.map(preset=><button key={preset.name} type="button" className="secondary-button" onClick={()=>setForm({...preset.colors})}><span className="theme-swatch" style={{background:preset.colors.primary}}/>{preset.name}</button>)}</div><div className="theme-fields">{themeFields.map(([key,label])=><label key={key} className="theme-color-field">{label}<div><input type="color" aria-label={label} value={form[key]} onChange={e=>setForm(f=>({...f,[key]:e.target.value}))}/><span>{form[key].toUpperCase()}</span></div></label>)}</div><div className="theme-preview" style={themeVariables(form)} aria-label="사이트 색상 미리보기"><div className="theme-preview-heading"><span className="kicker">BAYESIAN STATISTICS LABORATORY</span><h3>연구와 탐구를 연결하는 공간</h3><p>페이지 제목과 구분 영역의 색상을 확인하세요.</p></div><div className="theme-preview-body"><h3>연구실 소식</h3><p>본문과 배경, 링크와 버튼이 함께 어우러지는지 확인하세요.</p><span className="more">연구 분야 자세히 보기 →</span><div className="form-actions"><button type="button" className="primary">주요 버튼</button><button type="button" className="secondary-button">보조 버튼</button></div></div></div>{warnings.map(warning=><p className="notice" role="status" key={warning}>{warning}</p>)}<div className="form-actions"><button className="primary">{busy?'저장 중…':'디자인 저장'}</button><button type="button" className="secondary-button" onClick={()=>setForm({...defaultTheme})}>기본값 복원</button></div><p className="search-help">기본값 복원 후 저장하면 사이트 전체에 반영됩니다. 사진·로고·오류 및 삭제 색상은 유지됩니다.</p></fieldset><p role="status" className={error?'error':'form-feedback'}>{message|| (loading?'설정을 불러오는 중…':'')}</p></form></section>;
}
