import {ensureMemberApplication} from '@/lib/member-application';
import {requestedLabRole} from '@/lib/membership-role';
import {NextRequest,NextResponse} from 'next/server';
import {publishProfileDetails} from '@/lib/profile-details-server';
import {requireAdmin,privilegedDb} from '@/lib/supabase';
import {z} from 'zod';
import {revalidatePath,revalidateTag} from 'next/cache';
export async function GET(){const admin=await requireAdmin();if(!admin)return NextResponse.json({error:'관리자 권한이 필요합니다.'},{status:401});const {data,error}=await admin.db.from('profiles').select('id,display_name,academic_role,membership_status,created_at').eq('role','viewer').order('created_at',{ascending:false});const service=privilegedDb();if(!error&&data){const {data:members}=await admin.db.from('members').select('user_id,role');const roles=new Map((members||[]).map(member=>[member.user_id,member.role]));for(const row of data){if(roles.has(row.id))row.academic_role=roles.get(row.id)}}if(!error&&service&&data){await Promise.all(data.filter(row=>row.membership_status==='pending').map(async row=>{const {data:auth}=await service.auth.admin.getUserById(row.id);const role=auth.user&&requestedLabRole(auth.user.user_metadata);if(role)row.academic_role=role}))}return NextResponse.json(error?{error:'회원가입 설정 SQL(002_membership.sql)을 먼저 적용해주세요.',setup_needed:true}:{data},{status:error?503:200})}
export async function POST(req:NextRequest){const admin=await requireAdmin();if(!admin)return NextResponse.json({error:'관리자 권한이 필요합니다.'},{status:401});const p=z.object({id:z.string().uuid(),approve:z.boolean()}).safeParse(await req.json().catch(()=>null));if(!p.success)return NextResponse.json({error:'신청 정보를 확인해주세요.'},{status:400});const service=privilegedDb();if(service&&p.data.approve){const {data:auth,error:authError}=await service.auth.admin.getUserById(p.data.id);if(authError||!auth.user)return NextResponse.json({error:'가입 정보를 확인하지 못했습니다.'},{status:503});if(!auth.user.email_confirmed_at){const {error:confirmationError}=await service.auth.admin.updateUserById(p.data.id,{email_confirm:true});if(confirmationError)return NextResponse.json({error:'기존 가입 신청의 로그인 설정을 변경하지 못했습니다.'},{status:503})}try{await ensureMemberApplication(service,auth.user)}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'구성원 프로필 연결에 실패했습니다.'},{status:503})}const role=requestedLabRole(auth.user.user_metadata);if(role){const {error:roleError}=await service.from('members').update({role}).eq('user_id',p.data.id);if(roleError)return NextResponse.json({error:'연구실 역할을 반영하지 못했습니다.'},{status:503})}}const {error}=await admin.db.rpc('review_lab_member',{target_user:p.data.id,approve:p.data.approve});if(error)return NextResponse.json({error:error.message.includes('Email confirmation')?'기존 가입 신청 처리에 실패했습니다. 다시 승인해주세요.':'가입 신청 처리에 실패했습니다. 회원가입 설정 SQL 적용 상태를 확인해주세요.'},{status:400});revalidateTag('lab-public');revalidatePath('/','layout');{const service=privilegedDb();if(service){const [{data:auth},{data:member}]=await Promise.all([service.auth.admin.getUserById(p.data.id),admin.db.from('members').select('id').eq('user_id',p.data.id).maybeSingle()]);if(member&&auth.user?.user_metadata.profile_details){const result=await publishProfileDetails(service,member.id,auth.user.user_metadata.profile_details,p.data.approve);if(result.error)return NextResponse.json({error:'가입 승인 후 소속 정보 반영에 실패했습니다. 다시 승인해주세요.'},{status:503})}}}revalidateTag('lab-public');revalidatePath('/','layout');return NextResponse.json({ok:true})}

export async function DELETE(req:NextRequest){const admin=await requireAdmin();if(!admin)return NextResponse.json({error:'관리자 권한이 필요합니다.'},{status:401});const parsed=z.object({id:z.string().uuid()}).safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'삭제할 계정을 확인해주세요.'},{status:400});const service=privilegedDb();if(!service)return NextResponse.json({error:'계정 삭제 연결을 확인할 수 없습니다.'},{status:503});const {data:profile,error}=await service.from('profiles').select('role').eq('id',parsed.data.id).maybeSingle();if(error||!profile)return NextResponse.json({error:'가입 신청을 찾지 못했습니다.'},{status:404});if(profile.role!=='viewer')return NextResponse.json({error:'관리자와 소유자 계정은 이 메뉴에서 삭제할 수 없습니다.'},{status:403});const result=await service.rpc('withdraw_lab_account',{target_user:parsed.data.id});if(result.error)return NextResponse.json({error:'계정 삭제에 실패했습니다. 탈퇴 설정 SQL(004_account_withdrawal.sql)을 확인해주세요.'},{status:503});revalidateTag('lab-public');revalidatePath('/','layout');return NextResponse.json({ok:true})}
